version: '3'

services:
  db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
  api:
    build: strands-api
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=strands-api.py
    command: flask run --host=0.0.0.0
    volumes:
      - ./strands-api:/strands-api
    ports:
      - "5000:5000"
    depends_on:
      - db
  web:
    build: strands-ui-app
    environment:
      - DEBUG=strands-ui-app:*
      - NODE_ENV=development
    command: npm start
    volumes:
      - ./strands-ui-app:/strands-ui-app
      - /strands-ui-app/node_modules
    ports:
      - "8050:8050"
    links:
      - db
      - api
    depends_on:
      - db
      - api
  client:
    build: strands-ui-client
    command: npm start
    volumes:
      - ./strands-ui-client:/strands-ui-client
      - /strands-ui-client/node_modules
    ports:
      - "8080:8080"
    links:
      - web
    depends_on:
      - web
